name = "cfmail-frontend"
main = "worker.js"
compatibility_date = "2024-05-13"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"

[[services]]
binding = "BACKEND"
service = "cfmail-api"
environment = "production"
